export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';

export const RESQEST_ROBOTS_PENDING = 'RESQEST_ROBOTS_PENDING';
export const RESQEST_ROBOTS_SUCCESS  = 'RESQEST_ROBOTS_SUCCESS';
export const RESQEST_ROBOTS_FAILED = 'RESQEST_ROBOTS_FAILED';